await element to be attached before calling .play on it
otherwise Firefox 128 throws this error when setProcessor is called on track:
failed to play processor element
Object { room: undefined, roomID: undefined, participant: undefined, pID: undefined, trackID: undefined, source: "camera", muted: false, enabled: true, kind: "video", streamID: "{bbe7a482-313d-49e6-8d55-5dbe42d2c24f}", … }
enabled: true
error: DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
kind: "video"
muted: false
pID: undefined
participant: undefined
room: undefined
roomID: undefined
source: "camera"
streamID: "{bbe7a482-313d-49e6-8d55-5dbe42d2c24f}"
streamTrackID: "{ae53ec2f-9257-4f7e-9525-d7b2aa0ad809}"
trackID: undefined
<prototype>: Object { … }